### ISSUE TITLE
one can open the chest on another island

### ISSUE THREAD

**Issue by Gtafgu** [larryTheCoder/ASkyBlock#14] opened 2020-08-06 04:15 UTC
one can open the chest on another island

**Comment by larryTheCoder** [comment] 2020-08-06 08:55
Confirmed, I will push a fix for this plus others too

**Closed** 2020-08-06 10:44 UTC

**Comment by larryTheCoder** [comment] 2020-08-06 10:46
The issue is solved, tested it in my localhost machine, however if its still occur, I would like to know :)
